# Generated by Django 5.0.3 on 2024-03-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=10)),
                ('lang', models.CharField(max_length=50)),
                ('ph_no', models.IntegerField(max_length=10)),
                ('age', models.IntegerField(max_length=2)),
            ],
            options={
                'db_table': 'User_info',
            },
        ),
    ]
